/** 全站文案（与原型保持一致；「说人话、不指责、有分寸」三条语气原则）。 */

export const COPY = {
  homeTitle: '今天想学点什么？',
  homeSubtitle: '输入一段内容，颜宝帮你变成闯关题',
  inputPlaceholder: '粘贴一段笔记、讲义，或任何你想学的内容…',
  tooShort: '内容太短啦，再多描述一点（至少 20 字）',
  tooLong: '内容太长，建议精简到 2000 字以内',
  startGenerate: '开 始 生 成',
  tryThese: '试试这些',
  recentLearning: '最近学习',
  emptyRecords: '还没有学习记录',
  emptyRecordsHint: '在上面输入点什么，颜宝就开工了',
  resumeLearning: '继续上次的学习',
  generatingTitle: '颜宝正在读你的内容',
  generatingHint: '大约需要 20 秒',
  generatingSteps: ['① 理解内容', '② 梳理结构', '③ 准备出题'],
  generatingTips: ['正在理解你的内容…', '正在梳理知识结构…', '快要好了…'],
  outlineTitle: '知识大纲',
  outlineReadyTip: '梳理出 {n} 个知识点，可以改标题或删掉不想要的',
  outlineEditingHint: '编辑中… 点击标题即可改',
  outlineDeleteBlocked: '至少要保留 2 个知识点，不然没法出题',
  regenerate: '重新生成',
  startQuiz: '开始闯关',
  outlineFailedTitle: '这次没梳理成功',
  outlineFailedHint: '可能是内容太长或格式比较特殊，换个说法再试试？',
  outlineFailedTryTitle: '可以试试',
  outlineFailedTry: ['把长文档拆成两三段分别生成', '直接用一句话描述你想学的主题'],
  changeContent: '改内容',
  tryAgain: '再试一次',
  submitting: '正在出题…',
  submittingHint: '颜宝在给每个知识点出题，大约 30 秒',
  submit: '提 交',
  nextQuestion: '下 一 题',
  finishLevel: '完 成 本 关',
  nextLevel: '进入下一关',
  correctFeedback: '✓ 就是它',
  wrongFeedback: '这题有点绕，我们来看看',
  aiNotice: '内容由 AI 生成 · 有问题可点右上角 ⋯ 反馈',
  quitTitle: '先歇会儿？',
  quitHint: '进度会帮你留着，下次回来接着答',
  quitCurrent: '当前进度',
  quitContinue: '继续答题',
  quitLater: '退出，稍后再来',
  reportTitle: '这道题有什么问题？',
  reportHint: '你的反馈会让我们把题出得更准',
  reportReasons: ['答案有误', '表述不清楚 / 有歧义', '和之前某道题重复了', '其他问题'],
  reportCancel: '取 消',
  reportSubmit: '提交反馈',
  reportNotice: '同一题被 3 人反馈后会先下架复核',
  reportThanks: '谢谢反馈，我们会尽快复核',
  starTitle3: '通关！',
  accurateRate: '正确率 · 共 {n} 题',
  timeUsed: '用时',
  correctCount: '答对',
  knowledgePoints: '各知识点表现',
  notYet: '还没有学习记录，去试试第一个闯关吧',
  playAgain: '再来一次',
  viewRecords: '看学习记录',
  viewMistakes: '先看看错题',
  learnAgain: '再学一遍',
  mistakesSoon: '错题本马上就来，先再学一遍？',
  mineTitle: '我的',
  learner: '学习者',
  memberBadge: '非会员',
  notStarted: '还没有开始学习',
  studyCount: '学习次数',
  answeredCount: '累计答题',
  avgAccuracy: '平均正确率',
  studyDays: '已学习 {d} 天 · 连续 {s} 天',
  emptyMineTitle: '这里还空着',
  emptyMineHint: '去闯第一关，记录就会出现在这里',
  goStudy: '去学习',
  loadMore: '上拉加载更多 · 共 {n} 条',
  agreements: '用户协议 · 隐私政策 · 版本 v0.1.0',
  networkError: '网络打了个盹',
  networkErrorHint: '检查一下网络，然后点一下重试',
  retry: '重 试',
  noDifficulty: '难度 {stars}'
} as const
