"""initial schema

Revision ID: ba9c0649ba60
Revises: 
Create Date: 2026-09-17 14:37:14.406080
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text  # noqa: F401  automigrate 生成的是 Text()，需要这个名字

# 自动生成时 Alembic 只写了 app.db.types.UTCDateTime 的全名，没有带 import，这里补上
import app.db.types

revision: str = 'ba9c0649ba60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=64), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_member', sa.Boolean(), nullable=False),
    sa.Column('member_expire_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_openid', ['openid'], unique=True)

    op.create_table('knowledge_source',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_knowledge_source_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_source'))
    )
    with op.batch_alter_table('knowledge_source', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_source_user', ['user_id', 'created_at'], unique=False)

    op.create_table('knowledge_outline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('outline_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_source.id'], name=op.f('fk_knowledge_outline_source_id_knowledge_source')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_knowledge_outline_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_outline'))
    )
    with op.batch_alter_table('knowledge_outline', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_outline_user', ['user_id', 'created_at'], unique=False)

    op.create_table('attempt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('star', sa.SmallInteger(), nullable=True),
    sa.Column('started_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['outline_id'], ['knowledge_outline.id'], name=op.f('fk_attempt_outline_id_knowledge_outline')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_attempt_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempt'))
    )
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_user_started', ['user_id', 'started_at'], unique=False)
        batch_op.create_index('ix_attempt_user_status', ['user_id', 'status'], unique=False)

    op.create_table('level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('knowledge_point', sa.String(length=128), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['outline_id'], ['knowledge_outline.id'], name=op.f('fk_level_outline_id_knowledge_outline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_level')),
    sa.UniqueConstraint('outline_id', 'seq', name='uq_level_outline_seq')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('outline_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('answer_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('hint_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('quality_score', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], name=op.f('fk_question_level_id_level')),
    sa.ForeignKeyConstraint(['outline_id'], ['knowledge_outline.id'], name=op.f('fk_question_outline_id_knowledge_outline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question'))
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('ix_question_level_seq', ['level_id', 'seq'], unique=False)

    op.create_table('answer_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_answer_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempt.id'], name=op.f('fk_answer_record_attempt_id_attempt')),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_answer_record_question_id_question')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_answer_record_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_record'))
    )
    with op.batch_alter_table('answer_record', schema=None) as batch_op:
        batch_op.create_index('ix_answer_record_attempt', ['attempt_id'], unique=False)

    op.create_table('mistake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('wrong_count', sa.Integer(), nullable=False),
    sa.Column('mastery', sa.SmallInteger(), nullable=False),
    sa.Column('next_review_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_mistake_question_id_question')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_mistake_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mistake'))
    )
    with op.batch_alter_table('mistake', schema=None) as batch_op:
        batch_op.create_index('ix_mistake_user_next_review', ['user_id', 'next_review_at'], unique=False)

    op.create_table('question_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name=op.f('fk_question_report_question_id_question')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_question_report_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_report'))
    )
    with op.batch_alter_table('question_report', schema=None) as batch_op:
        batch_op.create_index('ix_question_report_question_status', ['question_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_report', schema=None) as batch_op:
        batch_op.drop_index('ix_question_report_question_status')

    op.drop_table('question_report')
    with op.batch_alter_table('mistake', schema=None) as batch_op:
        batch_op.drop_index('ix_mistake_user_next_review')

    op.drop_table('mistake')
    with op.batch_alter_table('answer_record', schema=None) as batch_op:
        batch_op.drop_index('ix_answer_record_attempt')

    op.drop_table('answer_record')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('ix_question_level_seq')

    op.drop_table('question')
    op.drop_table('level')
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_user_status')
        batch_op.drop_index('ix_attempt_user_started')

    op.drop_table('attempt')
    with op.batch_alter_table('knowledge_outline', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_outline_user')

    op.drop_table('knowledge_outline')
    with op.batch_alter_table('knowledge_source', schema=None) as batch_op:
        batch_op.drop_index('ix_knowledge_source_user')

    op.drop_table('knowledge_source')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_openid')

    op.drop_table('user')
    # ### end Alembic commands ###
